#####################
# Passwords
#
# Make sure that Passlib is installed with `pip install passlib`
# Run: `python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.hash('my_password'))"`
# Replace <my_password> with your actual password
#
#####################

# The name of the OS user (johndoe, ubuntu, vagrant)
username: vagrant
password: '$6$rounds=100000$vcEVMb1oJOPHy6ui$PTnvifu.xDG8cez.FBusjI18nwe9J/Hyms/IRgXSlsJwyGgSkEHEKRs658A8Lb7DzT6fSVF6Hh4aLolauXWm81'

webdev_password: '$6$rounds=100000$vcEVMb1oJOPHy6ui$PTnvifu.xDG8cez.FBusjI18nwe9J/Hyms/IRgXSlsJwyGgSkEHEKRs658A8Lb7DzT6fSVF6Hh4aLolauXWm81'


vars:
    db_root_pwd: "{{ db_root_pwd }}"

# MySQL root password
# mysql_password: PASSWORD
mysql_password: '$6$rounds=656000$T5vx3a8jbRXzMllO$c9Bt1FkZ47lBSjHp0y8qHdk2WQGLQtNB7ZceAkZkeXhMskAD5rNZtGKG3uMfFK.CEO7W0o5Df66tYp251Ghlb.'

tasks:
    - set_fact:
        db_root_pwd: "{{ lookup('env', 'DB_ROOT_PWD') }}"
      run_once: true
    - debug:
        var: db_root_pwd


vars:
    db_root_pwd1: "{{ db_root_pwd }}"
    - debug:
      var: db_root_pwd1

# Timezone
server_timezone: Europe/Amsterdam

# Locale
locale: en_US.UTF-8

#####################
#
# Hardening 
#
#####################

ssh_port: 22

fail2ban:
  config:
    ignoreip: 127.0.0.1/8
    bantime: 300
    maxretry: 6
    filter: sshd
    port: "{{ ssh_port }}"