- name: install pyenv
  import_role:
    name: staticdev.pyenv
  vars:
    pyenv_env: 'system'
    pyenv_global: ["3.8.16"]
    pyenv_python_versions: ["3.8.16"]
    pyenv_uninstall_python_w_wrong_configure_opts: False