---

- name: Add repository for latest node.js
  apt_repository: 
    repo='ppa:chris-lea/node.js' 
    state=present

- name: Install node.js (npm is included)
  apt: 
    name=nodejs
    update_cache=yes
    state=latest
