---
- name: Install epel-release to get access to certbot
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install nsupdate which is used by the certbot auth-hook
  ansible.builtin.yum:
    name: bind-utils
    state: present
  when: letsencrypt_cert is defined and letsencrypt_cert.challenge|default() == 'dns'

- name: Install Let's Encrypt Certbot client
  ansible.builtin.yum:
    name: certbot
    state: present

- name: Install certbot plugin 'apache' on webservers
  ansible.builtin.yum:
    name: python2-certbot-apache
    state: present
  when: letsencrypt_cert is defined and letsencrypt_cert.challenge|default() == 'http' and letsencrypt_http_auth == 'apache'

- name: Install certbot plugin 'nginx' on webservers
  ansible.builtin.yum:
    name: python2-certbot-nginx
    state: present
  when: letsencrypt_cert is defined and letsencrypt_cert.challenge|default() == 'http' and letsencrypt_http_auth == 'nginx'
