---
  
- name: prevent root login
  replace:
    dest=/etc/ssh/sshd_config
    regexp='^PermitRootLogin yes'
    replace='PermitRootLogin no'
    backup=yes
  notify: restart ssh

- name: We will enable Protocol 2. SSH by default works with Protocol 1. Protocol 2 is newer more secure and robust version introduced in 2006.
  lineinfile:
    path=/etc/ssh/sshd_config
    insertbefore='Include.*'
    line='Protocol 2'
    #  state=present
  notify: restart ssh  
