---


- name: "Protect su by limiting access only to admin group"
  group: 
    name=admin 
    state=present
    
- name: "usermod -aG admin {{ username }}"
  shell: usermod -aG admin {{ username }}
  
- name: "usermod -aG admin webdev"
  shell: usermod -aG admin webdev
  
- name: "dpkg-statoverride --update --add root admin 4750 /bin/su"
  command: dpkg-statoverride --update --force --add root admin 4750 /bin/su

        