- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

  tasks:

    - set_fact:
        db_root_pwd: "{{ lookup('env', 'DB_ROOT_PWD') }}"
      run_once: true

    - debug:
      msg:
        - "The DB_ROOT_PWD is {{ db_root_pwd }}"
        # var: db_root_pwd
    
  # - debug:
  #   - msg:
  #     - "The DB_ROOT_PWD is {{ db_root_pwd }}"

  roles:
    # - common
    # - unattended-upgrades
    # - users
    # - ansible-pyenv
    # - ansible-role-nginx
    # - mysql
    # - hardening


