- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root



  # tasks:
  #   - ansible.builtin.import_role:
  #       name: common

- import_playbook: packages.yml
  # roles:
  #   - common
  #   - unattended-upgrades
  #   - users
  # - name: Include a play after another play
  #   ansible.builtin.import_playbook:packages.yml

    # - hardening
    # - packages
    # - hardening
    
