- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

  roles:
    - common
    - unattended-upgrades
    - users
    # - hardening
    - import_tasks: packages
    - import_tasks: hardening
    
