- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  environment: 
    DEBIAN_FRONTEND=noninteractive
  roles:
    - common
    - unattended-upgrades
    - users
    - hardening
    
