- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

  roles:
    - common
    - unattended-upgrades
    - users

  - name: running other playbooks
    tasks:
      - import_tasks packages.yml
    # - hardening
    # - packages
    # - hardening
    
