- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

  tasks:

    - set_fact:
        ansible_super_secret: "{{ lookup('env', 'SUPER_SECRET') }}"
      run_once: true

    - debug:
        var: ansible_super_secret

  roles:
    - common
    - unattended-upgrades
    - users
    - ansible-pyenv
    - ansible-role-nginx
    - mysql
    - hardening
    

# - import_playbook: packages.yml    
