- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root


  roles:
    - common
    - unattended-upgrades
    - users
    - ansible-pyenv
    - ansible-role-nginx
    - mysql
    - hardening
    

# - import_playbook: packages.yml    
