---

- hosts: all
  sudo: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python3 and aptitude'
      raw: sudo apt-get -y install python-simplejson aptitude
  roles:
    - common
    - users
#    - hardening

    
  - import_tasks: packages.yml
  - import_tasks: users.yml

  #### Hardening should be the last step
  # - import_tasks: hardening.yml
